spring.application.name=SecurityApp
spring.datasource.url=jdbc:postgresql://localhost:5432/security-app
spring.datasource.username=postgres
spring.datasource.password=Tpomsm@2610.postgres6
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.data.jdbc.dialect=postgresql

#security configs
spring.security.user.name=manas
spring.security.user.password=pass
#spring.security.user.roles={"ADMIN"}

jwt.secretKey="fsdfjksdfklajdfgajoirjgoij48253y4t80u89fgijd9gha8berg98fdvidfpjgvijnpgv8"