spring.application.name=SecurityApp
spring.datasource.url=jdbc:postgresql://localhost:5432/security-app
spring.datasource.username=postgres
spring.datasource.password=Tpomsm@2610.postgres6
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.data.jdbc.dialect=postgresql

#security configs
spring.security.user.name=
spring.security.user.password=